"""
Manual mapping of KenPom team names to ESPN logo filenames.
This handles all the variations between the two sources.
"""

KENPOM_TO_ESPN = {
    "Abilene Christian": "abilene_christian",
    "Air Force": "air_force",
    "Akron": "akron",
    "Alabama": "alabama",
    "Alabama A&M": "alabama_am",
    "Alabama St.": "alabama_state",
    "Albany": "ualbany",
    "Alcorn St.": "alcorn_state",
    "American": "american_university",
    "Appalachian St.": "app_state",
    "Arizona": "arizona",
    "Arizona St.": "arizona_state",
    "Arkansas": "arkansas",
    "Arkansas Pine Bluff": "arkansas-pine_bluff",
    "Arkansas St.": "arkansas_state",
    "Army": "army",
    "Auburn": "auburn",
    "Austin Peay": "austin_peay",
    "BYU": "byu",
    "Ball St.": "ball_state",
    "Baylor": "baylor",
    "Bellarmine": "bellarmine",
    "Belmont": "belmont",
    "Bethune Cookman": "bethune_cookman",
    "Binghamton": "binghamton",
    "Boise St.": "boise_state",
    "Boston College": "boston_college",
    "Boston University": "boston_university",
    "Bowling Green": "bowling_green",
    "Bradley": "bradley",
    "Brown": "brown",
    "Bryant": "bryant",
    "Bucknell": "bucknell",
    "Buffalo": "buffalo",
    "Butler": "butler",
    "CSUN": "cal_state_northridge",
    "Cal Baptist": "california_baptist",
    "Cal Poly": "cal_poly",
    "Cal St. Bakersfield": "cal_state_bakersfield",
    "Cal St. Fullerton": "cal_state_fullerton",
    "California": "california",
    "Campbell": "campbell",
    "Canisius": "canisius",
    "Central Arkansas": "central_arkansas",
    "Central Connecticut": "central_connecticut",
    "Central Michigan": "central_michigan",
    "Charleston": "charleston",
    "Charleston Southern": "charleston_southern",
    "Charlotte": "charlotte",
    "Chattanooga": "chattanooga",
    "Chicago St.": "chicago_state",
    "Cincinnati": "cincinnati",
    "Clemson": "clemson",
    "Cleveland St.": "cleveland_state",
    "Coastal Carolina": "coastal_carolina",
    "Colgate": "colgate",
    "Colorado": "colorado",
    "Colorado St.": "colorado_state",
    "Columbia": "columbia",
    "Connecticut": "uconn",
    "Coppin St.": "coppin_state",
    "Cornell": "cornell",
    "Creighton": "creighton",
    "Dartmouth": "dartmouth",
    "Davidson": "davidson",
    "Dayton": "dayton",
    "DePaul": "depaul",
    "Delaware": "delaware",
    "Delaware St.": "delaware_state",
    "Denver": "denver",
    "Detroit Mercy": "detroit_mercy",
    "Drake": "drake",
    "Drexel": "drexel",
    "Duke": "duke",
    "Duquesne": "duquesne",
    "East Carolina": "east_carolina",
    "East Tennessee St.": "east_tennessee_state",
    "East Texas A&M": "east_texas_am",
    "Eastern Illinois": "eastern_illinois",
    "Eastern Kentucky": "eastern_kentucky",
    "Eastern Michigan": "eastern_michigan",
    "Eastern Washington": "eastern_washington",
    "Elon": "elon",
    "Evansville": "evansville",
    "FIU": "florida_international",
    "Fairfield": "fairfield",
    "Fairleigh Dickinson": "fairleigh_dickinson",
    "Florida": "florida",
    "Florida A&M": "florida_am",
    "Florida Atlantic": "florida_atlantic",
    "Florida Gulf Coast": "florida_gulf_coast",
    "Florida St.": "florida_state",
    "Fordham": "fordham",
    "Fresno St.": "fresno_state",
    "Furman": "furman",
    "Gardner Webb": "gardner_webb",
    "George Mason": "george_mason",
    "George Washington": "george_washington",
    "Georgetown": "georgetown",
    "Georgia": "georgia",
    "Georgia Southern": "georgia_southern",
    "Georgia St.": "georgia_state",
    "Georgia Tech": "georgia_tech",
    "Gonzaga": "gonzaga",
    "Grambling St.": "grambling",
    "Grand Canyon": "grand_canyon",
    "Green Bay": "green_bay",
    "Hampton": "hampton",
    "Harvard": "harvard",
    "Hawaii": "hawaii",
    "High Point": "high_point",
    "Hofstra": "hofstra",
    "Holy Cross": "holy_cross",
    "Houston": "houston",
    "Houston Christian": "houston_christian",
    "Howard": "howard",
    "IU Indy": "iu_indianapolis",
    "Idaho": "idaho",
    "Idaho St.": "idaho_state",
    "Illinois": "illinois",
    "Illinois Chicago": "uic",
    "Illinois St.": "illinois_state",
    "Incarnate Word": "incarnate_word",
    "Indiana": "indiana",
    "Indiana St.": "indiana_state",
    "Iona": "iona",
    "Iowa": "iowa",
    "Iowa St.": "iowa_state",
    "Jackson St.": "jackson_state",
    "Jacksonville": "jacksonville",
    "Jacksonville St.": "jacksonville_state",
    "James Madison": "james_madison",
    "Kansas": "kansas",
    "Kansas City": "kansas_city",
    "Kansas St.": "kansas_state",
    "Kennesaw St.": "kennesaw_state",
    "Kent St.": "kent_state",
    "Kentucky": "kentucky",
    "LIU": "long_island_university",
    "LSU": "lsu",
    "La Salle": "la_salle",
    "Lafayette": "lafayette",
    "Lamar": "lamar",
    "Le Moyne": "le_moyne",
    "Lehigh": "lehigh",
    "Liberty": "liberty",
    "Lindenwood": "lindenwood",
    "Lipscomb": "lipscomb",
    "Little Rock": "little_rock",
    "Long Beach St.": "long_beach_state",
    "Longwood": "longwood",
    "Louisiana": "louisiana_lafayette",
    "Louisiana Monroe": "ul_monroe",
    "Louisiana Tech": "louisiana_tech",
    "Louisville": "louisville",
    "Loyola Chicago": "loyola_chicago",
    "Loyola MD": "loyola_maryland",
    "Loyola Marymount": "loyola_marymount",
    "Maine": "maine",
    "Manhattan": "manhattan",
    "Marist": "marist",
    "Marquette": "marquette",
    "Marshall": "marshall",
    "Maryland": "maryland",
    "Maryland Eastern Shore": "maryland_eastern_shore",
    "Massachusetts": "umass",
    "McNeese": "mcneese",
    "Memphis": "memphis",
    "Mercer": "mercer",
    "Mercyhurst": "mercyhurst",
    "Merrimack": "merrimack",
    "Miami FL": "miami",
    "Miami OH": "miami_oh",
    "Michigan": "michigan",
    "Michigan St.": "michigan_state",
    "Middle Tennessee": "middle_tennessee",
    "Milwaukee": "milwaukee",
    "Minnesota": "minnesota",
    "Mississippi": "ole_miss",
    "Mississippi St.": "mississippi_state",
    "Mississippi Valley St.": "mississippi_valley_state",
    "Missouri": "missouri",
    "Missouri St.": "missouri_state",
    "Monmouth": "monmouth",
    "Montana": "montana",
    "Montana St.": "montana_state",
    "Morehead St.": "morehead_state",
    "Morgan St.": "morgan_state",
    "Mount St. Mary's": "mount_st_marys",
    "Murray St.": "murray_state",
    "N.C. State": "nc_state",
    "NJIT": "njit",
    "Navy": "navy",
    "Nebraska": "nebraska",
    "Nebraska Omaha": "omaha",
    "Nevada": "nevada",
    "New Hampshire": "new_hampshire",
    "New Haven": "new_haven",
    "New Mexico": "new_mexico",
    "New Mexico St.": "new_mexico_state",
    "New Orleans": "new_orleans",
    "Niagara": "niagara",
    "Nicholls": "nicholls",
    "Norfolk St.": "norfolk_state",
    "North Alabama": "north_alabama",
    "North Carolina": "north_carolina",
    "North Carolina A&T": "north_carolina_at",
    "North Carolina Central": "north_carolina_central",
    "North Dakota": "north_dakota",
    "North Dakota St.": "north_dakota_state",
    "North Florida": "north_florida",
    "North Texas": "north_texas",
    "Northeastern": "northeastern",
    "Northern Arizona": "northern_arizona",
    "Northern Colorado": "northern_colorado",
    "Northern Illinois": "northern_illinois",
    "Northern Iowa": "northern_iowa",
    "Northern Kentucky": "northern_kentucky",
    "Northwestern": "northwestern",
    "Northwestern St.": "northwestern_state",
    "Notre Dame": "notre_dame",
    "Oakland": "oakland_golden",
    "Ohio": "ohio",
    "Ohio St.": "ohio_state",
    "Oklahoma": "oklahoma",
    "Oklahoma St.": "oklahoma_state",
    "Old Dominion": "old_dominion",
    "Oral Roberts": "oral_roberts",
    "Oregon": "oregon",
    "Oregon St.": "oregon_state",
    "Pacific": "pacific",
    "Penn": "pennsylvania",
    "Penn St.": "penn_state",
    "Pepperdine": "pepperdine",
    "Pittsburgh": "pittsburgh",
    "Portland": "portland",
    "Portland St.": "portland_state",
    "Prairie View A&M": "prairie_view_am",
    "Presbyterian": "presbyterian",
    "Princeton": "princeton",
    "Providence": "providence",
    "Purdue": "purdue",
    "Purdue Fort Wayne": "purdue_fort_wayne",
    "Queens": "queens_university",
    "Quinnipiac": "quinnipiac",
    "Radford": "radford",
    "Rhode Island": "rhode_island",
    "Rice": "rice",
    "Richmond": "richmond",
    "Rider": "rider",
    "Robert Morris": "robert_morris",
    "Rutgers": "rutgers",
    "SIUE": "siu_edwardsville",
    "SMU": "smu",
    "Sacramento St.": "sacramento_state",
    "Sacred Heart": "sacred_heart",
    "Saint Francis": "saint_francis",
    "Saint Joseph's": "saint_josephs",
    "Saint Louis": "saint_louis",
    "Saint Mary's": "saint_marys",
    "Saint Peter's": "saint_peters",
    "Sam Houston St.": "sam_houston",
    "Samford": "samford",
    "San Diego": "san_diego",
    "San Diego St.": "san_diego_state",
    "San Francisco": "san_francisco",
    "San Jose St.": "san_josé_state",
    "Santa Clara": "santa_clara",
    "Seattle": "seattle_u",
    "Seton Hall": "seton_hall",
    "Siena": "siena",
    "South Alabama": "south_alabama",
    "South Carolina": "south_carolina",
    "South Carolina St.": "south_carolina_state",
    "South Dakota": "south_dakota_coyotes",
    "South Dakota St.": "south_dakota_state_jackrabbits",
    "South Florida": "south_florida",
    "Southeast Missouri": "southeast_missouri_state",
    "Southeastern Louisiana": "se_louisiana",
    "Southern": "southern",
    "Southern Illinois": "southern_illinois",
    "Southern Indiana": "southern_indiana",
    "Southern Miss": "southern_miss",
    "Southern Utah": "southern_utah",
    "St. Bonaventure": "st_bonaventure",
    "St. John's": "st_johns",
    "St. Thomas": "st_thomas-minnesota",
    "Stanford": "stanford",
    "Stephen F. Austin": "stephen_f_austin",
    "Stetson": "stetson",
    "Stonehill": "stonehill",
    "Stony Brook": "stony_brook",
    "Syracuse": "syracuse",
    "TCU": "tcu",
    "Tarleton St.": "tarleton_state",
    "Temple": "temple",
    "Tennessee": "tennessee",
    "Tennessee Martin": "ut_martin",
    "Tennessee St.": "tennessee_state",
    "Tennessee Tech": "tennessee_tech",
    "Texas": "texas",
    "Texas A&M": "texas_am",
    "Texas A&M Corpus Chris": "texas_am_corpus_christi",
    "Texas Southern": "texas_southern",
    "Texas St.": "texas_state",
    "Texas Tech": "texas_tech",
    "The Citadel": "citadel",
    "Toledo": "toledo",
    "Towson": "towson",
    "Troy": "troy",
    "Tulane": "tulane",
    "Tulsa": "tulsa",
    "UAB": "uab",
    "UC Davis": "uc_davis",
    "UC Irvine": "uc_irvine",
    "UC Riverside": "uc_riverside",
    "UC San Diego": "uc_san_diego",
    "UC Santa Barbara": "uc_santa_barbara",
    "UCF": "ucf",
    "UCLA": "ucla",
    "UMBC": "umbc",
    "UMass Lowell": "umass_lowell",
    "UNC Asheville": "unc_asheville",
    "UNC Greensboro": "unc_greensboro",
    "UNC Wilmington": "unc_wilmington",
    "UNLV": "unlv",
    "USC": "usc",
    "USC Upstate": "south_carolina_upstate",
    "UT Arlington": "ut_arlington",
    "UT Rio Grande Valley": "ut_rio_grande_valley",
    "UTEP": "utep",
    "UTSA": "utsa",
    "Utah": "utah",
    "Utah St.": "utah_state",
    "Utah Tech": "utah_tech",
    "Utah Valley": "utah_valley",
    "VCU": "vcu",
    "VMI": "vmi",
    "Valparaiso": "valparaiso",
    "Vanderbilt": "vanderbilt",
    "Vermont": "vermont",
    "Villanova": "villanova",
    "Virginia": "virginia",
    "Virginia Tech": "virginia_tech",
    "Wagner": "wagner",
    "Wake Forest": "wake_forest",
    "Washington": "washington",
    "Washington St.": "washington_state",
    "Weber St.": "weber_state",
    "West Georgia": "west_georgia",
    "West Virginia": "west_virginia",
    "Western Carolina": "western_carolina",
    "Western Illinois": "western_illinois",
    "Western Kentucky": "western_kentucky",
    "Western Michigan": "western_michigan",
    "Wichita St.": "wichita_state",
    "William & Mary": "william_mary",
    "Winthrop": "winthrop",
    "Wisconsin": "wisconsin",
    "Wofford": "wofford",
    "Wright St.": "wright_state",
    "Wyoming": "wyoming",
    "Xavier": "xavier",
    "Yale": "yale",
    "Youngstown St.": "youngstown_state",
}
